### ISSUE TITLE
Only CJ courier unit test is failed.

### ISSUE THREAD

**Issue by wisedog** [purpleworks/delibird#4]
Hi contributors. 

I just forked your awesome application, but I met "failure" message. 
Only CJ test is failed although Travis CI indicates "PASSING". 
Is there any dependency of system? First time I tried to go test, gcc is needed. 

$ go test -v -coverprofile=couriers.coverprofile ./couriers
=== RUN   TestCJCourier

  CJ test
    Invalid tracking number test .
    Start courier test x
    Complete courier test x

Failures:
- C:/workspace/golang/src/github.com/purpleworks/delibird/couriers/cj_test.go
  Line 41:
  Expected: '51'
  Actual:   '0'
  (Should be equal)
- C:/workspace/golang/src/github.com/purpleworks/delibird/couriers/cj_test.go
  Line 51:
  Expected: '91'
  Actual:   '0'
  (Should be equal)

3 total assertions

--- FAIL: TestCJCourier (0.10s)
=== RUN   TestCourier

**Comment by subicura** [comment]
Hi, @wisedog 
It seems html encoding issue. CJ html file encoded with EUC-KR. 
Please tell me, OS/Go Version.
